name: Run 10 Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10-dind
        options: --privileged
        ports:
          - 4566:4566
          - 4510:4510

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=1.29.2
          curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" \
          -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Kill any processes using port 4566
        run: |
          sudo lsof -i :4566 | awk 'NR!=1 {print $2}' | xargs -r sudo kill -9

      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.test.yml build
        continue-on-error: true

      - name: Start Docker containers
        run: |
          docker-compose -f docker-compose.test.yml up -d
        continue-on-error: true

      - name: Check Docker container status
        run: |
          docker-compose -f docker-compose.test.yml ps
          docker-compose -f docker-compose.test.yml logs

      - name: Run tests
        run: |
          docker-compose -f docker-compose.test.yml run test
        continue-on-error: true

      - name: Print test results
        run: |
          docker-compose -f docker-compose.test.yml logs test

      - name: Shut down Docker containers
        run: |
          docker-compose -f docker-compose.test.yml down
        continue-on-error: true
